mail:
  define:
    enabled: true
    custom-format: false
  redefine:
    enabled: true
    custom-format: false
  addmember:
    enabled: true
    custom-format: false
  removemember:
    enabled: true
    custom-format: false
  addowner:
    enabled: true
    custom-format: false
  removeowner:
    enabled: true
    custom-format: false
  remove:
    enabled: true
    custom-format: false

# La hauteur des claims (la couche la plus haute et la couche la plus basse)
expand-selection-y:
  expand: true
  max: 255
  min: 0

# Les paramètres à ajouter au claim
# %sender%  : Joueur qui exécute la commande
# %target%  : Joueur qui est ciblé par la commande
# (Ne sont utilisé que pour les joueurs, pas pour les groupes)
#
# Valeurs possibles pour 'set-tp' : "none", "here", "northwest", "northeast", "southwest", "southeast"
define:
  set-tp: "northwest"
  owner:
    - "%target%"
  owner-group: []
  member: []
  member-group:
    - "modo"

redefine:
  set-tp: "northwest"
  owner: []
  owner-group: []
  member: []
  member-group: []