mail:
  define:
    enabled: true
    custom-format: false
  redefine:
    enabled: true
    custom-format: false
  addmember:
    enabled: true
    custom-format: false
  removemember:
    enabled: true
    custom-format: false
  addowner:
    enabled: true
    custom-format: false
  removeowner:
    enabled: true
    custom-format: false
  remove:
    enabled: true
    custom-format: false

# La hauteur des claims (la couche la plus haute et la couche la plus basse)
expand-selection-y:
  expand: true
  max: 255
  min: 0