mail:
  define:
    enabled: true
    custom-format: false
  redefine:
    enabled: true
    custom-format: false
  addmember:
    enabled: true
    custom-format: false
  removemember:
    enabled: true
    custom-format: false
  addowner:
    enabled: true
    custom-format: false
  removeowner:
    enabled: true
    custom-format: false
  remove:
    enabled: true
    custom-format: false


# La hauteur des claims (la couche la plus haute et la couche la plus basse)
expand-selection-y:
  expand: true
  max: 255
  min: 0


# Les paramètres à ajouter au claim
# %sender%  : Joueur qui exécute la commande
# %target%  : Joueur qui est ciblé par la commande
# (Ne sont utilisé que pour les joueurs, pas pour les groupes)
#
# Valeurs possibles pour 'set-tp' : "none", "here", "northwest", "northeast", "southwest", "southeast"
define:
  set-tp: "northwest"
  tp-modifier:
    x: 0.0
    y: 0.0
    z: 0.0
  owner:
    - "%target%"
  owner-group: []
  member: []
  member-group:
    - "modo"
  flags:

redefine:
  set-tp: "northwest"
  tp-modifier:
    x: 0.0
    y: 0.0
    z: 0.0
  owner: []
  owner-group: []
  member: []
  member-group: []
  flags:

# Dans cette section, le 'rayon' correspond à la moitié du côté du carré centré sur le joueur qui execute la commande
near:
  # Le rayon par défaut si aucun rayon n'est spécifié
  default-distance: 200
  # Le rayon maximal que peut entrer un joueur qui n'a pas la permission de mettre n'importe quel rayon
  base-max-distance: 200
  # Le temps pendant lequel le joueur ne peut pas refaire la commande.
  # Exprimé en milliseconde
  cooldown: 1000
  # Le nombre d'entrée pour lequel il faut nettoyer le cache inutile
  cooldown-size-clear-check: 4

listadd:
  # Le temps pendant lequel doit être gardé en mémoire le résulat
  # de la commande pour un joueur donné dans un monde donné.
  # Exprimé en milliseconde
  cache-period: 4000
  # Le nombre d'entrée pour lequel il faut nettoyer le cache inutile
  cache-size-clear-check: 4
  # Le nombre de régions par page
  region-by-page: 10

statistic:
  help: false
  define: true
  redefine: true
  addmember: true
  removemember: true
  addowner: true
  removeowner: true
  remove: true
  info: false
  teleport: false
  here: false
  near: false
  listadd: false
  stats: false
  pillar: false


# Laisser une liste vide autorise la commande dans tous les mondes
#
# Si la liste contient un ou plusieurs éléments, la commande n'est
# autorisée que dans les mondes dont le nom figure dans la liste
#
#
# Exemple:
#
# worlds:
#   help: []
#   define:
#     - "map1"
#     - "map2"
#
# La commande help est autorisée partout tandis que la commande define
# n'est autorisée que dans les mondes 'map1' et 'map2'
#

worlds:
  help: []
  define: []
  redefine: []
  addmember: []
  removemember: []
  addowner: []
  removeowner: []
  remove: []
  info: []
  teleport: []
  here: []
  near: []
  listadd: []
  stats:
    reset: []
    show: []
  pillar: []